FROM node:14-alpine

RUN mkdir /app
WORKDIR /app
RUN npm install -g serve
COPY ./package.json ./package.json
RUN npm i
COPY tsconfig.json tsconfig.json
COPY ./src ./src
COPY ./public ./public

RUN npm run build

CMD serve -s build
