services:
  mongodb:
    restart: always

  server:
    command: sh -c "npm run build && npm run prod"
    expose:
      - 5000
    volumes:
      - server-built:/server/built
    restart: always
    environment:
      - DB_USERNAME=mayanaB
      - DB_PASSWORD=mayana1234
      - DB_NAME=baammcluster
      - NODE_ENV=production

  client:
    command: sh -c "npm run build"
    expose:
      - 3000
    volumes:
      - client-build:/app/build
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:8000
  nginx:
    image: nginx:1.19.10
    restart: always
    ports:
      - ${GATEWAY_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - client-build:/client-build
      - server-built:/server-built

volumes:
  client-build:
  server-built: