version: '3'

services:
  db:
    restart: always

  bam-backend:
    command: npm run dev
    stdin_open: true
    volumes:
      - ./server/src:/app/src
    ports:
      - 4000:8000
    environment:
      - DB_USERNAME=mayanaB
      - DB_PASSWORD=mayana1234
      - DB_NAME=baammcluster
      - NODE_ENV=development
      - JWT_KEY=baamm-secret-key
      - DB_URL=mongodb+srv://Totow:jecode4wcs@baammcluster.wxcnu.mongodb.net/db_baamm?retryWrites=true&w=majority

  bam-frontend:
    command: npm run start
    stdin_open: true
    volumes:
      - ./client:/app
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:5000