version: '3'

services:
  mongodb:
    restart: always

  server:
    command: npm run prod
    expose:
      - 5000
    volumes:
      - server-built:/server/built
    restart: always
    environment:
      - DB_USERNAME=mayanaB
      - DB_PASSWORD=mayana1234
      - DB_NAME=baammcluster
      - NODE_ENV=production
      - JWT_KEY=toto

  client:
    command: sh -c "npm run build"
    expose:
      - 3000
    volumes:
      - client-build:/app/build
    environment:
      - NODE_ENV=production
      # pour tester les requêtes en local
      #- REACT_APP_API_URL=http://localhost:8000
      # pour déployer
      - REACT_APP_API_URL=https://staging.baam.wns.wilders.dev/api

  nginx:
    image: nginx:1.19.10
    restart: always
    ports:
      - ${GATEWAY_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - client-build:/client-build
      - server-built:/server-built
      - ./nginx/logs:/var/log/nginx

volumes:
  client-build:
  server-built: