version: '3'

services:
  mongodb:
    restart: always

  server:
    command: npm run prod
    expose:
      - 5000
    volumes:
      - server-built:/server/built
    restart: always
    environment:
      - DB_USERNAME=mayanaB
      - DB_PASSWORD=mayana1234
      - DB_NAME=baammcluster
      - NODE_ENV=production
      - JWT_KEY=baamm-secret-key
      - DB_URL=mongodb+srv://Totow:jecode4wcs@baammcluster.wxcnu.mongodb.net/db_baamm?retryWrites=true&w=majority

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=https://staging.baam.wns.wilders.dev

  nginx:
    image: nginx:1.19.10
    restart: always
    ports:
      - ${GATEWAY_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - client-build:/client-build
      - ./nginx/logs:/var/log/nginx

volumes:
  client-build:
  server-built: