name: ci

on:
  push:
    branches: dev

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
         name: buildclient
         run: cd client && docker build -t mayana64/${{ secrets.DOCKERHUB_REPO }} . && docker push mayana64/${{ secrets.DOCKERHUB_REPO }}
