name: ci

on:
  push:
    branches: dev

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - 
        name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - 
        name: change to client
        run: cd client
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test
